version: '3.8' # Use a valid and modern version

services:
  sustainovate-backend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: sustainovate-backend-container
    restart: always
    ports:
      - "4000:4000"
    volumes:
      - ./logs:/app/logs
    env_file:
      - .env