version: "0.1"
services:
  sustainovate-backend:
    build: .
    container_name: sustainovate-container
    restart: always
    ports:
      - "4000:4000"
    volumes:
      - ./logs:/app/logs
    env_file:
      - .env