version: "3.8"

services:
  sustainovate-backend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: sustainovate-backend-container
    restart: always
    ports:
      - "4000:4000"
    volumes:
      - ./logs:/app/logs
    env_file:
      - .env

  prom-server:
    image: prom/prometheus
    container_name: prometheus-container
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus-config.yml:/etc/prometheus/prometheus.yml

  grafana:
    image: grafana/grafana:latest
    container_name: grafana-container
    ports:
      - "3300:3000" # Changed from 3000:3000
    volumes:
      - grafana-data:/var/lib/grafana
      - ./grafana-datasource.yml:/etc/grafana/provisioning/datasources/datasource.yml
    restart: always
    environment:
      - GF_SERVER_ROOT_URL=https://sustainovate.mainak.me/grafana
    depends_on:
      - prom-server

volumes:
  grafana-data: {} # This creates a persistent volume for Grafana data