services:
  sustainovate-backend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: sustainovate-backend-container
    restart: always
    ports:
      - "4000:4000"
    volumes:
      - ./logs:/app/logs
    env_file:
      - .env

  prom-server:
    image: prom/prometheus
    container_name: prometheus-container
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus-config.yml:/etc/prometheus/prometheus.yml
      - prometheus_data:/prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--web.external-url=https://api.mainak.me/prometheus'

  grafana:
    image: grafana/grafana:latest
    container_name: grafana-container
    ports:
      - "3300:3000" # external:internal
    volumes:
      - grafana-data:/var/lib/grafana
      - ./grafana-datasource.yml:/etc/grafana/provisioning/datasources/datasource.yml
    restart: always
    environment:
      - GF_SERVER_ROOT_URL=https://api.mainak.me/grafana
    depends_on:
      - prom-server

volumes:
  prometheus_data:
  grafana-data:
