global:
  scrape_interval: 3s

scrape_configs:
  - job_name: prometheus
    static_configs:
      - targets: ["api.mainak.me"]
      # - targets: ["api.mainak.me"]
      # - targets: ["192.168.0.:4000"]